// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Collections;

namespace FloofReport.Models
{
    public partial class Animal
    {
        public Animal()
        {
            Visualevents = new HashSet<Visualevent>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public DateOnly Dateofbirth { get; set; }
        public DateOnly? Dateofadoption { get; set; }
        public string Race { get; set; }
        public BitArray Sex { get; set; }

        public virtual ICollection<Visualevent> Visualevents { get; set; }
    }
}