// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FloofReport.Models
{
    public partial class Cage
    {
        public Cage()
        {
            Cageareas = new HashSet<Cagearea>();
            Visualevents = new HashSet<Visualevent>();
        }

        public int Id { get; set; }
        public string Location { get; set; }
        public string Beddingtype { get; set; }
        public short Beddingdepth { get; set; }
        public string Size { get; set; }

        public virtual ICollection<Cagearea> Cageareas { get; set; }
        public virtual ICollection<Visualevent> Visualevents { get; set; }
    }
}